

image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

services:
  - docker:dind

before_script:
  - echo "Running before script"

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Running job build"
    - mvn ${MAVEN_CLI_OPTS} compile

test:
  stage: test
  script:
    - echo "Running job test"
    - mvn ${MAVEN_CLI_OPTS} test
