version: "3.7"

services:

  poc-db:
    image: mysql/mysql-server:8.0.18
    container_name: poc-db
    ports:
      - ${MYSQL_ADMIN_PORT}:3306
    volumes:
      - poc-db-data:/var/lib/mysql
    networks:
      - poc
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      ENVIRONMENT: ${ENV}

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"

      MYSQL_DATABASE: "poc"
      MYSQL_USER: "poc"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


  poc-web-api:
    image: epotters/poc-web-api:0.1-SNAPSHOT
    container_name: poc-web-api
    ports:
      - 18002:8002
    networks:
      - poc
      - epo-external
    restart: always
    depends_on:
      - poc-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poc-web-api.rule=Host(`poc.${HOST}`)"
      - "traefik.http.routers.poc-web-api.entrypoints=web"
#      - "traefik.http.routers.poc-web-api.middlewares=traefik-forward-auth@file"
    environment:
      ENVIRONMENT: "${ENV}"
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: "jdbc:mysql://poc-db:3306/poc?useSSL=false&serverTimezone=Europe/Amsterdam"
      SPRING_DATASOURCE_USERNAME: "poc"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
      SPRING_APPLICATION_JSON: "{\"spring.jpa.hibernate.ddl-auto\": \"create\"}"


  poc-web-gui:
    image: epotters/poc-web-gui-angular:1.0-SNAPSHOT
    container_name: poc-web-gui
    ports:
    - 4200:80 # Can not be run together with ng serve (same port)
    volumes:
    - ./poc-web-gui/app-config:/usr/share/nginx/app-config
    networks:
      - poc
      - epo-external
    restart: always
    environment:
      ENVIRONMENT: "${ENV}"


volumes:
  poc-db-data:


networks:
  poc:
  epo-external:
    external: true
