version: "3.2"

services:

  poc-db:
    image: mysql/mysql-server:8.0.18
    container_name: poc-db-dev
    ports:
      - 13307:3306
    volumes:
      - poc-db-data:/var/lib/mysql
    networks:
      - poc
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      ENVIRONMENT: "dev"

      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"

      MYSQL_DATABASE: "poc"
      MYSQL_USER: "poc"
      MYSQL_PASSWORD: "b1vidh"


  poc-web-api:
    image: epotters/poc-web-api:0.1-SNAPSHOT
    container_name: poc-web-api-dev
    ports:
      - 18002:8002
    networks:
      - poc
      - epo-external-dev
    restart: always
    depends_on:
      - poc-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poc-web-api.rule=Host(`poc.localhost`)"
      - "traefik.http.routers.poc-web-api.entrypoints=web"
#      - "traefik.http.routers.poc-web-api.middlewares=traefik-forward-auth@file"
    environment:
      ENVIRONMENT: "dev"
      SPRING_PROFILES_ACTIVE: "development"
      SPRING_DATASOURCE_URL: "jdbc:mysql://poc-db:3306/poc?useSSL=false&serverTimezone=Europe/Amsterdam"
      SPRING_DATASOURCE_USERNAME: "poc"
      SPRING_DATASOURCE_PASSWORD: "b1vidh"
      SPRING_APPLICATION_JSON: "{\"spring.jpa.hibernate.ddl-auto\": \"create\"}"


  poc-web-gui:
    image: epotters/poc-web-gui-angular:1.0-SNAPSHOT
    container_name: poc-web-gui-dev
    ports:
    - 4200:80 # Can not be run together with ng serve (same port)
    volumes:
    - ./poc-web-gui/app-config:/usr/share/nginx/app-config
    networks:
      - poc
      - epo-external-dev
    restart: always
    depends_on:
      - poc-api
    environment:
      ENVIRONMENT: "dev"


volumes:
  poc-db-data:


networks:
  poc:
  epo-external-dev:
    external: true
