
# Embedded server
server:
  contextPath: /poc
  port: 8002


# REST
spring:
  data:
    rest:
      base-path: /api


# Security (OAuth2)

security:
  oauth2:
    client:
      # clientId: bd1c0a783ccdd1c9b9e4
      # clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      clientId: eb66c494b9c0a6913db6
      clientSecret: 7f123163c9808fd8b7893a8b03250e93f227f4b5
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form

      authentiationScheme: query
      tokenName: oauth_token
      scope: profile email

  resource:
    userInfoUri: https://api.github.com/user
    preferTokenInfo: false


# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
    org:
      hibernate: INFO


