
# Embedded server
server:
  context-path: /poc
  port: 8002


# REST
spring:
  data:
    rest:
      base-path: /api

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  # Data
  datasource:
    url: jdbc:mysql://localhost:3306/poc_dev
    username: poc_dev
    password: b1vidh
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    # validate or create-drop
    hibernate:
      ddl-auto: create-drop
      # See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes
      use-new-id-generator-mappings: true
    show-sql: true



management:
  context-path: /actuator


# Security
security:
  user:
    name: epo
    password: 12345
    role: USER

  # Security (OAuth2)
  oauth2:
    client:
      clientId: eb66c494b9c0a6913db6
      clientSecret: 7f123163c9808fd8b7893a8b03250e93f227f4b5
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form

      authenticationScheme: query
      tokenName: oauth_token
      scope: profile email

    resource:
      user-info-uri: https://api.github.com/user
      # token-info-uri:
      prefer-token-info: false


# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: INFO


