version: "3.7"

services:

  poc-db:
    image: mysql/mysql-server:8.0.21
    container_name: poc-db
    ports:
      - 3307:3306
    volumes:
      - poc-db-data:/var/lib/mysql
    networks:
      - poc
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      ENVIRONMENT: "prd"
      MYSQL_ROOT_HOST: "%"
#      MYSQL_DATABASE: "poc"
#      MYSQL_USER: "poc"
#      MYSQL_PASSWORD: "b1vidh"


  poc-web-api:
    image: epotters/poc-web-api:0.1
    container_name: poc-web-api
    ports:
      - 8002:8002
    networks:
      - poc
    restart: always
    depends_on:
      - poc-db
    environment:
      ENVIRONMENT: "prd"
      SPRING_DATASOURCE_URL: "jdbc:mysql://poc-db:3306/poc?useSSL=false&serverTimezone=Europe/Amsterdam"
#      SPRING_DATASOURCE_USERNAME: poc
#      SPRING_DATASOURCE_PASSWORD: b1vidh
#      SPRING_APPLICATION_JSON: "{\"spring.jpa.hibernate.ddl-auto\": \"create\"}"

  poc-web-gui:
    image: nginx:alpine
    container_name: poc-web-gui
    ports:
      - 10080:80
    volumes:
      - ./poc-web-gui/app:/usr/share/nginx/html:ro
    networks:
      - poc
    restart: always
    environment:
      ENVIRONMENT: "prd"

volumes:
  poc-db-data:


networks:
  poc:
