# Custom properties
poc:
  security-realm: POC Realm
  oauth:
    tokenTimeout: 2400


# Embedded server
server:
  servlet:
    contextPath: /poc
  port: 8002



# Actuators
management:
  endpoints:
    web:
      base-path: /actuator


# REST
spring:
  profiles:
    active: development
  data:
    rest:
      base-path: /api
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
  banner:
    location: classpath:banner.txt


  # Persistence
  datasource:
    url: jdbc:mysql://localhost:3306/poc?serverTimezone=Europe/Amsterdam
    username: poc
    password: b1vidh

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true



# Logging
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: INFO


