
# Logging
debug: true



spring:
  # Data
  datasource:
    url: jdbc:mysql://localhost:3306/poc_dev?useSSL=false
    username: poc_dev
    password: b1vidh

  banner:
      location: classpath:dev/banner.txt


# Logging
logging:
  file: target/log/poc.log
