spring:

  # Data
  datasource:
    url: jdbc:mysql://localhost:13307/poc?useSSL=false&serverTimezone=Europe/Amsterdam
    username: poc
    password: b1vidh

  jpa:
    hibernate:
      ddl-auto: create-drop

  banner:
      location: classpath:dev/banner.txt


# Logging
debug: true

logging:
  file: target/log/poc.log