# Embedded server
server:
  servlet:
    contextPath: /poc
  port: 8002


# Actuators
management:
  endpoints:
    web:
      base-path: /actuator

# REST
spring:
  data:
    rest:
      base-path: /api
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  banner:
    location: classpath:banner.txt


  #  # Persistence: DB will be provided externally, see: docker-compose.yml
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/poc?serverTimezone=Europe/Amsterdam
  #    username: poc
  #    password: b1vidh

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true

  # OAuth Resource server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.localhost.lab/auth/realms/epo/protocol/openid-connect/certs


cors:
  allowed-origins:
    - http://localhost:4200


# Logging
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: INFO

