
# Embedded server
server:
  servlet:
    contextPath: /poc
  port: 8002


# REST
spring:
  profiles:
    active: development
  data:
    rest:
      base-path: /api
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
  banner:
    location: classpath:banner.txt


  # Data
  datasource:
    url: jdbc:mysql://localhost:3306/poc?serverTimezone=Europe/Amsterdam
    username: poc
    password: b1vidh
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      # See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes
#      use-new-id-generator-mappings: true
    show-sql: true


poc:
  oauth:
    tokenTimeout: 2400
  security-realm: POC Realm

# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: INFO


