spring:

  # Data
  datasource:
    url: jdbc:mysql://localhost:13307/poc?useSSL=false&serverTimezone=Europe/Amsterdam
    username: poc
    password: b1vidh

  jpa:
    hibernate:
      ddl-auto: update  # create-drop

  banner:
      location: classpath:dev/banner.txt

#  security:
#    oauth2:
#      client:
#        registration:
#          # @see https://console.developers.google.com/apis/ to create your client credentials
#          google:
#            provider: google
#            client-id: 831648620820-c56ksoupbvl5603gkjvk5mb64lc253gt.apps.googleusercontent.com
#            client-secret: 1pIsztS3eGvTK190ckBGeiSL
#            client-authentication-method: basic
#            authorization-grant-type: authorization_code
#            scope:
#              - openid
#              - email
#              - profile
#              - https://www.googleapis.com/auth/tasks.readonly
#        provider:
#          google:
#            issuer-uri: https://accounts.google.com

# Logging
debug: true

logging:
  file:
    name: target/log/poc.log
