version: "3.2"

services:

  poc-db:
    image: mysql/mysql-server:8.0.15
    container_name: poc-db-dev
    ports:
      - 13307:3306
    volumes:
      - poc-db-data:/var/lib/mysql
    networks:
      - poc
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      ENVIRONMENT: "dev"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "poc"
      MYSQL_USER: "poc"
      MYSQL_PASSWORD: "b1vidh"


  poc-web-api:
    image: epotters/poc-web-api:0.1-SNAPSHOT
    container_name: poc-web-api-dev
    ports:
      - 18002:8002
    networks:
      - poc
    restart: always
    depends_on:
      - poc-db
    environment:
      ENVIRONMENT: "dev"
      SPRING_PROFILES_ACTIVE: development
      SPRING_DATASOURCE_URL: "jdbc:mysql://poc-db:3306/poc?useSSL=false&serverTimezone=Europe/Amsterdam"
      SPRING_DATASOURCE_USERNAME: poc
      SPRING_DATASOURCE_PASSWORD: b1vidh
      SPRING_APPLICATION_JSON: "{\"spring.jpa.hibernate.ddl-auto\": \"create\"}"


volumes:
  poc-db-data:


networks:
  poc: